name: Docs
on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: Build documentation
        run: ./gradlew dokkaHtmlMultiModule
        
      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          branch: master
          folder: build/dokka/htmlMultiModule
        

